<a href="https://colab.research.google.com/github/threegenie/studying_pytorch/blob/main/02_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> 1D with Numpy

In [1]:
import numpy as np

In [2]:
t = np.array([0,1,2,3,4,5,6])

In [3]:
print('벡터의 차원 : ',t.ndim)

벡터의 차원 :  1


In [4]:
print('벡터의 크기 : ',t.shape)

벡터의 크기 :  (7,)


(7,) = (1,7) = 1 x 7의 크기를 가지는 벡터

> 파이토치 텐서 선언

In [5]:
import torch

In [6]:
te = torch.IntTensor([0,1,2,3,4,5,6])

실수로 만드려면 torch.FloatTensor

In [7]:
print(te.dim())  # rank. 즉, 차원
print(te.shape)  # shape
print(te.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [8]:
print(te[0], te[1], te[-1])  # 인덱스로 접근
print(te[2:5], te[4:-1])    # 슬라이싱
print(te[:2], te[3:])       # 슬라이싱

tensor(0, dtype=torch.int32) tensor(1, dtype=torch.int32) tensor(6, dtype=torch.int32)
tensor([2, 3, 4], dtype=torch.int32) tensor([4, 5], dtype=torch.int32)
tensor([0, 1], dtype=torch.int32) tensor([3, 4, 5, 6], dtype=torch.int32)


> 2D 텐서 만들기

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [11]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])




---



In [12]:
t = torch.IntTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]
                      ])
print(t)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [13]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [14]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2,  5,  8, 11], dtype=torch.int32)
torch.Size([4])


tensor를 float와 int로 선언한 것을 비교하면, int로 선언하면 tensor를 슬라이싱하거나 그대로 출력할 때 데이터 타입이 붙는다. 

- 관련해서 추가 정리

```
텐서는 각 데이터 형태별로 정의되어 있습니다.
torch.FloatTensor : 32bit float point
torch.LongTensor : 64bit signed integer
GPU 상에서 계산할 때에는 torch.cuda.FloatTensor를 사용합니다. 일반적으로 Tensor는 FloatTensor라고 생각하면 됩니다.
어떤 형태의 텐서이건 torch.tensor라는 함수로 작성할 수 있습니다.
텐서에서의 사칙연산은 같은 타입의 텐서 간 또는 텐서와 파이썬의 스칼라 값 사이에서만 가능합니다.
텐서간이라도 타입이 다르면 연산이 되지 않습니다. FloatTensor와 DoubleTensor간의 사칙연산은 오류가 발생합니다.
```
https://gaussian37.github.io/dl-pytorch-basic/


> 브로드캐스팅

In [15]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

In [16]:
print(m1 + m2)

tensor([[5., 5.]])


In [17]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [19]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])




```
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```



> 곱셈

In [20]:
# 행렬 곱셈 - .matmul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(m1.matmul(m2)) # 2 x 1

tensor([[ 5.],
        [11.]])


In [21]:
# 원소별 곱셈  - .mul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(m1 * m2) # 2 x 2

print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


> 평균

In [22]:
# 평균 - .mean
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [24]:
print(t.mean(dim=0))

tensor([2., 3.])




```
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
```



In [25]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])




```
# 실제 연산 결과는 (2 × 1)
[1. 5]
[3. 5]
```



> 덧셈

In [26]:
# 덧셈 - .sum
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


> 최대, 아그맥스

In [28]:
# 최대 - 원소의 최대값 리턴
# 아그맥스 - 최대값 가진 인덱스 리턴

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


> 뷰(View) 

원소의 수를 유지하면서 텐서의 크기 변경, numpy의 reshape와 같은 역할

In [30]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [31]:
# 3차원에서 2차원 텐서로 변경
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [32]:
# 3차원 텐서의 크기 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


> 연결(concatenate)

In [33]:
x = torch.FloatTensor([[1, 2], 
                       [3, 4]])
y = torch.FloatTensor([[5, 6], 
                       [7, 8]])

In [34]:
print(torch.cat([x, y], dim=0)) #dim=0이므로 첫번째 차원을 늘림

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [35]:
print(torch.cat([x, y], dim=1)) 

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
